#!/bin/bash
"""
GPS Ambulance Detection - Terminal Usage Guide

This script provides quick commands for running the GPS-based ambulance detection system.
"""

echo "🚑 GPS-Based Ambulance Detection System"
echo "========================================"
echo ""
echo "📋 SETUP COMMANDS:"
echo "------------------"
echo "# 1. Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# 2. Start GPS Server (Terminal 1)"
echo "uvicorn gps_server:app --reload"
echo ""
echo "# 3. Run Ambulance Simulation (Terminal 2)"
echo "python simulate_ambulance.py"
echo ""
echo "# 4. Test Vehicle Detection (Terminal 3)"
echo "python tests/test_detector.py --source assets/sample_video.mp4"
echo ""
echo "🧪 TESTING COMMANDS:"
echo "--------------------"
echo "# Test GPS utilities"
echo "python gps_utils.py"
echo ""
echo "# Test integration"
echo "python test_gps_integration.py"
echo ""
echo "# Check GPS server health"
echo "curl http://localhost:8000/health"
echo ""
echo "# Get active ambulances"
echo "curl http://localhost:8000/ambulances"
echo ""
echo "📊 MONITORING:"
echo "---------------"
echo "# View GPS server logs (Terminal 1)"
echo "# View simulation progress (Terminal 2)"
echo "# View detection results (Terminal 3)"
echo ""
echo "🔧 CONFIGURATION:"
echo "------------------"
echo "# Edit camera location in config.py:"
echo "# CAMERA_LAT = 26.9124"
echo "# CAMERA_LON = 75.7873"
echo "# EMERGENCY_DISTANCE_KM = 1.0"
echo ""
echo "📁 NEW FILES:"
echo "-------------"
echo "gps_server.py          # FastAPI GPS server"
echo "gps_utils.py            # Distance calculations"
echo "simulate_ambulance.py   # GPS simulation"
echo "test_gps_integration.py # Integration tests"
echo "GPS_README.md           # Full documentation"
echo ""
echo "✅ INTEGRATION COMPLETE:"
echo "------------------------"
echo "VehicleDetector.detect() now returns:"
echo "{"
echo "  'vehicles': [...],"
echo "  'count': int,"
echo "  'emergency': bool,      # vision_emergency OR gps_emergency"
echo "  'gps_emergency': bool,  # GPS-based emergency status"
echo "  'raw_result': ...,"
echo "}"
echo ""
echo "🚨 EMERGENCY TRIGGERED WHEN:"
echo "----------------------------"
echo "- Ambulance visible in camera (vision)"
echo "- Ambulance within 1km of camera (GPS)"
echo ""
echo "🎯 READY FOR PRODUCTION!"</content>
<parameter name="filePath">/Users/soumaydhrub/~/Library/Application Support/Cursor/traffic-ai/gps_usage_guide.sh